CREATE TABLE [dbo].[OCRDocument]
(
	[OCRDocumentId] INT NOT NULL IDENTITY(1, 1) CONSTRAINT PK_OCRDocumentId PRIMARY KEY CLUSTERED,
	[OCRResult] VARCHAR(MAX) NULL,
	[DateCreated] DATETIME2(0) NOT NULL CONSTRAINT DF_OCRDocument_DateCreated DEFAULT(GETUTCDATE()),
	[DateCompleted] DATETIME2(0) NULL,
	[StorageContainer] VARCHAR(64) NOT NULL,
	[StorageKey] VARCHAR(64) NOT NULL
)
