-- =============================================
-- Author:        kkilburn
-- Create date: 2020-12-22
-- Description:   loads all the providers
-- =============================================
CREATE PROCEDURE [dbo].[load_provider] 
AS
BEGIN
   -- SET NOCOUNT ON added to prevent extra result sets from
   -- interfering with SELECT Statements.
   SET NOCOUNT ON;

   INSERT INTO [stage].[Provider]
            ([NPI]
            ,[ProviderType]
            ,[Name]
            ,[AddressLine1]
            ,[AddressLine2]
            ,[City]
            ,[State]
            ,[PostalCode]
            ,[PostalCodeArea]
            ,[TelephoneNumber]
            ,[FaxNumber]
            ,[EmailAddress]
            ,[FirstName]
            ,[MiddleName]
            ,[LastName]
            ,[suffix]
            ,[ProfessionalSuffix]
            ,[SigningName]
            ,[Latitude]
            ,[Longitude]
            ,[ServiceCount]
            ,[IsNPIActive]
            ,[CanSign]
            ,[IsActiveInSutureSign]
            ,[IsCollaborator]
            ,[IsSigner]
            ,[IsSender]
            ,[SutureCreatedAt]
            ,[SutureCustomerType]
            ,[SutureFacilityId]
            ,[SutureFacilityTypeId]
            ,[SuturePrimaryFacilityId]
            ,[SuturePrimaryFacilityName]
            ,[SutureUserId]
            ,[SutureUserTypeId]
            ,[SutureCloseDate]
            ,[IsNetworkProvider]
            ,[SutureUpdatedAt])
   SELECT [NPI]
        , [ProviderType]
        , [Name]
        , [AddressLine1]
        , [AddressLine2]
        , [City]
        , [State]
        , [PostalCode]
        , [PostalCodeArea]
        , [Phone]
        , [Fax]
        , [Email]
        , [FirstName]
        , [MiddleName]
        , [LastName]
        , [suffix]
        , [ProfessionalSuffix]
        , [SigningName]
        , [Latitude]
        , [Longitude]
        , [ServiceCount]
        , [IsNPIActive]
        , [CanSign]
        , [IsActive]
        , [IsCollaborator]
        , [IsSigner]
        , [IsSender]
        , [SutureCreatedAt]
        , [SutureCustomerType]
        , [SutureFacilityId]
        , [SutureFacilityTypeId]
        , [SuturePrimaryFacilityId]
        , [SuturePrimaryFacilityName]
        , [SutureUserId]
        , [SutureUserTypeId]
        , [SutureCloseDate]
        , [IsNetworkProvider]
        , [UpdatedAt]
     FROM [import].[Provider] p
    WHERE p.IsNetworkProvider = 1 
       OR (ProviderType = 2 AND ServiceCount > 0)

END
