CREATE VIEW [dbo].[PatientMatchLog]
AS 
	SELECT [MatchPatientLogID]
          ,[SubmittedFirstName]     [FirstName]
          ,[SubmittedMiddleName]    [MiddleName]
          ,[SubmittedLastName]      [LastName]
          ,[SubmittedMaidenName]    [MaidenName]
          ,[SubmittedSuffix]        [Suffix] 
          ,[SubmittedDOB]           [Birthdate]
          ,[SubmittedGender]        [Gender]
          ,[SubmittedSSN]           [SocialSecurityNumber]
          ,[SubmittedLastSSN]       [SocialSecuritySerial]
          ,[SubmittedMedicare#]     [MedicareNumber]
          ,[SubmittedMedicaid#]     [MedicaidNumber]
          ,[SubmittedMedicaidState] [MedicaidState]
          ,[SubmittedFacilityMRN]   [FacilityMRN]
          ,[SubmittedAddress1]      [Address1]
          ,[SubmittedAddress2]      [Address2]
          ,[SubmittedCity]          [City]
          ,[SubmittedState]         [State]
          ,[SubmittedZip]           [Zip]
          ,[SubmittedHomePhone]     [HomePhone]
          ,[SubmittedWorkPhone]     [WorkPhone]
          ,[SubmittedMobilePhone]   [Mobile]
          ,[SubmittedOtherPhone]    [OtherPhone]
          ,[SubmittedPrimaryPhone]  [PrimaryPhone]
          ,[MatchAlgorithmID]
          ,[MatchedPatient]
          ,[NeedsReview]
          ,[ManuallyMatched] 
          ,[ManuallyMatchedBy] 
          ,[ManuallyMatchedOn] 
          ,[MultiplePatientsMatched]
          ,[SimilarPatientHigh]
          ,[SimilarPatientLow]
          ,[ProcessingStartTime]
          ,[ProcessingEndTime]
          ,[RecordsEvaluated]
          ,[CreateDate]
          ,[SubmittedBy]            [MemberId]
          ,[SubmittedByFacility]    [FacilityId]
          ,[SubmittedSource]        [Source]
          ,[SourceDescription]
          ,[SubmittedMedicareMBI]
          ,[IsSelfPay] 
          ,[IsPrivateInsurance]
          ,[IsMedicareAdvantage]
	  FROM [$(SutureSignWeb)].[dbo].MatchPatientLog
