//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SutureHealth.Documents.Testing {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.2.0.0")]
    internal sealed partial class ci : global::System.Configuration.ApplicationSettingsBase {
        
        private static ci defaultInstance = ((ci)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ci())));
        
        public static ci Default {
            get {
                return defaultInstance;
            }
        }
    }
}
