CREATE TABLE [dataScraping].[ScrapedPatientDetail]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [ExternalId] NVARCHAR(50) NULL, 
    [FirstName] NVARCHAR(50) NULL, 
    [MiddleName] NVARCHAR(50) NULL, 
    [LastName] NVARCHAR(50) NULL, 
    [DateOfBirth] DATETIME NULL, 
    [Gender] NVARCHAR(50) NULL, 
    [MaritalStatus] NVARCHAR(50) NULL, 
    [SexualOrientation] NVARCHAR(50) NULL, 
    [AttendedPhysician] NVARCHAR(50) NULL, 
    [Address] NVARCHAR(250) NULL, 
    [City] NVARCHAR(25) NULL, 
    [Country] NVARCHAR(25) NULL, 
    [PostalCode] NVARCHAR(25) NULL, 
    [PatientBalance] NVARCHAR(20) NULL, 
    [InsuranceBalance] NVARCHAR(20) NULL, 
    [TotalBalance] NVARCHAR(20) NULL, 
    [Occupation] NVARCHAR(50) NULL, 
    [Employer] NVARCHAR(50) NULL, 
    [Language] NVARCHAR(50) NULL, 
    [Ethnicity] NVARCHAR(50) NULL, 
    [Race] NVARCHAR(50) NULL, 
    [FamilySize] NVARCHAR(10) NULL, 
    [MonthlyIncome] NVARCHAR(20) NULL, 
    [Religion] NVARCHAR(50) NULL, 
    [DeceaseDate] NVARCHAR(50) NULL, 
    [DeceaseReason] NVARCHAR(50) NULL, 
    [SSN] NVARCHAR(50) NULL, 
    [CreatedAt] DATETIME NOT NULL, 
    [URL] NVARCHAR(250) NULL
)
